services:
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ppdatabase
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: